import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/navigation";
import { Cinzel, Gowun_Batang } from "next/font/google";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Verdicta",
  description: "Generated by create next app",
};

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-cinzel",
  display: "swap",
  weight: ["500"],
});

const gowun = Gowun_Batang({
  subsets: ["latin"],
  variable: "--font-gowun",
  display: "swap",
  weight: ["400"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`antialiased selection:text-background selection:bg-primary ${gowun.className} ${cinzel.variable} text-lg`}
      >
        <Navigation />
        <div className="min-h-screen max-w-6xl px-10 mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
