import type { Metadata } from "next";
import "./globals.css";
import NavigationWrapper from "./components/NavigationWrapper";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Verdicta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased selection:text-background selection:bg-primary">
        <NavigationWrapper />
        <div className="min-h-screen pt-15 max-w-6xl mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
